# Generated by Django 5.0.6 on 2026-06-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('verdict', models.CharField(choices=[('original', 'Original'), ('counterfeit', 'Counterfeit'), ('suspicious', 'Suspicious')], max_length=20)),
                ('confidence', models.FloatField()),
                ('engine', models.CharField(choices=[('yolov8', 'YOLOv8'), ('simulation', 'Simulation')], default='simulation', max_length=20)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('reported', models.BooleanField(default=False)),
                ('scanned_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='brands.brand')),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanAnalysisPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=8)),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('score', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warning'), ('fail', 'Fail')], max_length=10)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_points', to='scans.scan')),
            ],
            options={
                'db_table': 'scan_analysis_points',
                'ordering': ['order'],
            },
        ),
    ]
