# Generated by Django 5.0.6 on 2026-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/details/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/docs/%Y/%m/'),
        ),
    ]
