# Generated by Django 5.0.6 on 2026-06-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_detail_image_scan_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='document_image',
        ),
    ]
