# Generated by Django 5.0.6 on 2026-06-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Oddiy Foydalanuvchi'), ('entrepreneur', 'Tadbirkor')], default='user', max_length=20),
        ),
    ]
