# Generated by Django 5.0.6 on 2026-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='📦', max_length=8)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food_beverage', 'Food & Beverage'), ('cosmetics', 'Cosmetics'), ('pharma', 'Pharma'), ('accessories', 'Accessories'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=30)),
                ('protection_level', models.CharField(choices=[('standard', 'Standard'), ('enhanced', 'Enhanced'), ('maximum', 'Maximum')], default='standard', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['-created_at'],
            },
        ),
    ]
