# Generated by Django 5.0.6 on 2026-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('clothing', 'Kiyim-kechak'), ('perfumery', 'Parfumeriya')], default='clothing', max_length=30),
        ),
    ]
